#!/usr/bin/env bash
# Display information about subdomains.

# Function to get DNS information for a subdomain
get_dns_info() {
    local URL="$1.$2"
    local RESPONSE=$(dig "$URL")
    local IP=$(echo "$RESPONSE" | awk '/ANSWER SECTION:/ {getline; print $5}')
    local RECORDTYPE=$(echo "$RESPONSE" | awk '/ANSWER SECTION:/ {getline; print $4}')
    echo "The subdomain $1 is a $RECORDTYPE record and points to $IP"
}

# Check if the correct number of arguments are provided
if [ $# -eq 1 ]; then
    # Loop through predefined subdomains
    for DOMAIN in 'www' 'lb-01' 'web-01' 'web-02'; do
        get_dns_info "$DOMAIN" "$1"
    done
elif [ $# -eq 2 ]; then
    get_dns_info "$2" "$1"
else
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi
